

path:
    dataInfo: './dataInfo.mat'

dir:
    derivative: 'xxxxx' # Specify the directory that contains the subdirectory "derivative."
    annotation: '{derivative_dir}/derivatives/annotation/' 
    mask: '{derivative_dir}/derivatives/preprocessed_data/'
    resp: '{derivative_dir}/derivatives/preprocessed_data/'
    stim: '{derivative_dir}/derivatives/feature/'
    froi: '{derivative_dir}/derivatives/localizer/'
    accuracy: '{derivative_dir}/derivatives/accuracy/'
    ridge: '{derivative_dir}/derivatives/ridge/'
    pycortex_db: '{derivative_dir}/derivatives/pycortex_db/'

movieInfo:
    titleLabels: [0,1,1,2,3,4,5,6,7,8,8]
    titleNames: ['breakingbad', 'bigbangtheory', 'bigbangtheory', 'crown', 'heroes', 'suits', 'dreamgirls', 'glee', 'mentalist', 'gis', 'gis']
    episodeNames: ['vol1.ep1', 'vol1.ep1', 'vol1.ep2', 'vol1.ep1', 'vol1.ep1', 'vol1.ep1', '-', 'vol1.ep1', 'vol1.ep1', 'vol1.ep1', 'vol1.ep2']

subjectInfo:
    names: ['S01', 'S02', 'S03', 'S04', 'S05', 'S06']
    pycortex_db_names: ['sub-S01', 'sub-S02', 'sub-S03', 'sub-S04', 'sub-S05', 'sub-S06']
    loadIntems_no: [0,1,2,3,4,5]

annotInfo:
    annotTypes: ['speechTranscription', 'objectiveAnnot50chara', 'story', 'speechTranscription_EN']
    abbreviations_annot: ['speech', 'object', 'story', 'speechEn']
    modelNames: ['GPT2medium_jp', 'GPT2medium_jp', 'GPT2medium_jp', 'GPT2medium_en']
    abbreviations_model: ['gpt2mjp', 'gpt2mjp', 'gpt2mjp', 'gpt2men']
    modelSubNames: 
        GPT2medium_jp: ['layer6_mean', 'layer12_mean', 'layer18_mean', 'layer24_mean']
        GPT2medium_en: ['layer6_mean', 'layer12_mean', 'layer18_mean', 'layer24_mean']
        abbreviations: ['l6m', 'l12m', 'l18m', 'l24m'] 
    
ridgeInfo:
    stim_delays: [2,4,6]
    modelNames: ['GPT2medium_jp', 'GPT2medium_en']
    modelSubNames: 
        GPT2medium_jp: ['layer6_mean', 'layer12_mean', 'layer18_mean', 'layer24_mean']
        GPT2medium_en: ['layer6_mean', 'layer12_mean', 'layer18_mean', 'layer24_mean']
        abbreviations: ['l6m', 'l12m', 'l18m', 'l24m']
    #fileBase: 

localizerInfo:
    locIDs: [1,2,3,4,5,6,7,8,9,10,11]
    locLabels: ['KathleenRing', 'KathleenWedge', 'FFA_OFA', 'PPA_OPA_RSC', 'Motion', 'Auditory', 'Language', 'Motor', 'WorkingMemory', 'ToM', 'MiniGame']
    locNames: ['Retinotopy_angle', 'Retinotopy_eccentricity', 'Object_face', 'Object_place', 'Motion', 'Auditory', 'Language', 'Motor', 'Working_memory', 'Theory_of_Mind', 'Mini_game']
    plotTypes: ['weight', 'weight', 'stat', 'stat', 'stat', 'stat', 'stat', 'weight', 'stat', 'stat', 'weight']
    fileBase: 'sub-{:s}_froi_{:s}.mat'
    ROIs: ['V1', 'V2', 'V3', 'FFA', 'OFA', 'PPA', 'MT+', 'AC', 'S1H', 'S1M', 'S1F', 'M1H', 'M1M', 'M1F', 'IPS', 'FEF']


pycortexInfo:
    dataSetName: 'fs_fullhead'    
    
    